### ISSUE TITLE
Could gene -> id be moved to gene_id?

### ISSUE THREAD

**Issue by Relequestual** [ga4gh/mme-apis#90]
Under the variant object, we have a `gene` attribute which has an attribute `id`. Is there any need for this? Why not have `gene_id`?

**Comment by buske** [comment]
In the current structure, we can also have a `label` attribute, and additional gene identifiers (e.g. François' `_ensemblID`). In general, it's part of the shift to having things be represented as something close to an OntologyTerm type, with `id`, `source`, and `label`/`name` fields.

**Comment by Relequestual** [comment]
Hum yes I see the argument for that. The label / name field would be considered the canonical term, in which case, why wouldn't we just use that?

**Comment by buske** [comment]
Since all the other `label` fields are optional, semantically unformalized human-readable descriptions, I'd avoid using it to communicate a standardized term like a gene symbol. The gene symbol could certainly be used as the `label` if the `id` is a non-gene-symbol ID, but I don't think it makes sense to constrain the label field in this way.

**Comment by Relequestual** [comment]
Agreed
